apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: hello-app
  template:
    metadata:
      labels:
        type: hello-app
    spec:
     containers:
     - name: nginx
       image: ofandoud/hello-nginx:v1.2
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-service	
spec:
  type: LoadBalancer
  selector:
    type: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
