apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: prod-deploy
  template:
    metadata:
      labels:
        type: prod-deploy
    spec:
     containers:
     - name: nginx
       image: ofandoud/hello-world:latest
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-deploy-service	
spec:
  type: LoadBalancer
  selector:
    type: prod-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
